[programs.devnet]
payproof = "declare_id!(EJkAW3JKPKDFUw3b6gVvJMnhY21CR9qg7a8nqaZrZM7p);"

[provider]
cluster = "devnet"

[programs.localnet]
payproof = "declare_id!(EJkAW3JKPKDFUw3b6gVvJMnhY21CR9qg7a8nqaZrZM7p);"
